added Uhc command
HGLabor/hglabor-bot pull request #1
Opened 2021-06-24 14:21 UTC by Maquzowastaken

added Uhc command

2021-06-24 14:26 UTC, mooziii commented on src/main/kotlin/de/hglabor/command/commands/UhcCommand.kt
> +                        "Another HGLabor UHC event. \n" +
![](https://i.imgur.com/M4LNF4O.png)

2021-06-24 14:27 UTC, mooziii commented
ja is ok aber eig wollte ich dafür in der lobby ein item adden damit dass dann alles automatisch geht

2021-06-24 14:29 UTC, mooziii requested changes

2021-06-24 14:29 UTC, mooziii commented on src/main/kotlin/de/hglabor/command/commands/UhcCommand.kt
> +    name ="Uhc",
mach das komplett lowercase dann geht es

2021-06-24 14:43 UTC, mooziii commented
OBSI

2021-06-24 14:43 UTC, mooziii approved these changes

2021-06-24 14:43 UTC, merged

2021-06-24 21:11 UTC, NooMacroo commented
3 reviews....

2021-06-25 06:37 UTC, mooziii commented
@NooMacroo was dagegen